# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pycharmworkspace\Intellectual-testing-system\interface\Windows\admin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(451, 389)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.questionThemeComboBox = QtWidgets.QComboBox(self.tab)
        self.questionThemeComboBox.setObjectName("questionThemeComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.questionThemeComboBox)
        self.themeTestButton = QtWidgets.QPushButton(self.tab)
        self.themeTestButton.setObjectName("themeTestButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.themeTestButton)
        self.errorTestLabel = QtWidgets.QLabel(self.tab)
        self.errorTestLabel.setText("")
        self.errorTestLabel.setObjectName("errorTestLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.errorTestLabel)
        self.genetalTestButton = QtWidgets.QPushButton(self.tab)
        self.genetalTestButton.setObjectName("genetalTestButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.genetalTestButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 407, 238))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.userListLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.userListLabel.setText("")
        self.userListLabel.setObjectName("userListLabel")
        self.verticalLayout_5.addWidget(self.userListLabel)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.changeStatusButton = QtWidgets.QPushButton(self.tab_4)
        self.changeStatusButton.setObjectName("changeStatusButton")
        self.verticalLayout_4.addWidget(self.changeStatusButton)
        self.BlockButton = QtWidgets.QPushButton(self.tab_4)
        self.BlockButton.setObjectName("BlockButton")
        self.verticalLayout_4.addWidget(self.BlockButton)
        self.changePasswordButton = QtWidgets.QPushButton(self.tab_4)
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.verticalLayout_4.addWidget(self.changePasswordButton)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 394, 440))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.photoView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.photoView.setObjectName("photoView")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.photoView)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_5)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.nameLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLine.setObjectName("nameLine")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLine)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.surnameLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.surnameLine.setObjectName("surnameLine")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.surnameLine)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.faternityLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.faternityLine.setObjectName("faternityLine")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.faternityLine)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dateOfBirth = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateOfBirth)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.group = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.group)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.question = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.question.setObjectName("question")
        self.question.addItem("")
        self.question.addItem("")
        self.question.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.question)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.answerLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.answerLine.setObjectName("answerLine")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.answerLine)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.emailLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.emailLine.setObjectName("emailLine")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.emailLine)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.phoneLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.phoneLine.setObjectName("phoneLine")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.phoneLine)
        self.acceptChangesButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.acceptChangesButton.setObjectName("acceptChangesButton")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.acceptChangesButton)
        self.DeleteUser = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.DeleteUser.setObjectName("DeleteUser")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.DeleteUser)
        self.errorChangesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.errorChangesLabel.setText("")
        self.errorChangesLabel.setObjectName("errorChangesLabel")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.errorChangesLabel)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 407, 325))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.statisticLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.statisticLabel.setObjectName("statisticLabel")
        self.verticalLayout_6.addWidget(self.statisticLabel)
        self.viewGraphicsButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.viewGraphicsButton.setObjectName("viewGraphicsButton")
        self.verticalLayout_6.addWidget(self.viewGraphicsButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.groupsOfQuestionsBox = QtWidgets.QComboBox(self.tab_5)
        self.groupsOfQuestionsBox.setObjectName("groupsOfQuestionsBox")
        self.verticalLayout_7.addWidget(self.groupsOfQuestionsBox)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.questionsComboBox = QtWidgets.QComboBox(self.tab_5)
        self.questionsComboBox.setObjectName("questionsComboBox")
        self.verticalLayout_7.addWidget(self.questionsComboBox)
        self.editQuestionButton = QtWidgets.QPushButton(self.tab_5)
        self.editQuestionButton.setObjectName("editQuestionButton")
        self.verticalLayout_7.addWidget(self.editQuestionButton)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.hideQuestionButton = QtWidgets.QPushButton(self.tab_5)
        self.hideQuestionButton.setObjectName("hideQuestionButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hideQuestionButton)
        self.hideGroupOfQuestionsButton = QtWidgets.QPushButton(self.tab_5)
        self.hideGroupOfQuestionsButton.setObjectName("hideGroupOfQuestionsButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hideGroupOfQuestionsButton)
        self.deleteGroupOfQuestionsButton = QtWidgets.QPushButton(self.tab_5)
        self.deleteGroupOfQuestionsButton.setObjectName("deleteGroupOfQuestionsButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deleteGroupOfQuestionsButton)
        self.deleteQuestionButton = QtWidgets.QPushButton(self.tab_5)
        self.deleteQuestionButton.setObjectName("deleteQuestionButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.deleteQuestionButton)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.AddQuestionButton = QtWidgets.QPushButton(self.tab_5)
        self.AddQuestionButton.setObjectName("AddQuestionButton")
        self.verticalLayout_7.addWidget(self.AddQuestionButton)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        AdminWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Система тестирования"))
        self.label.setText(_translate("AdminWindow", "Выберите тему"))
        self.themeTestButton.setText(_translate("AdminWindow", "Пройти тематический тест"))
        self.genetalTestButton.setText(_translate("AdminWindow", "Пройти итоговый тест"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AdminWindow", "Тестирование"))
        self.changeStatusButton.setText(_translate("AdminWindow", "Изменить статус"))
        self.BlockButton.setText(_translate("AdminWindow", "Заблокировать"))
        self.changePasswordButton.setText(_translate("AdminWindow", "Запросы на смену пароля"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("AdminWindow", "Менеджер пользователей"))
        self.label_14.setText(_translate("AdminWindow", "Фото"))
        self.pushButton_5.setText(_translate("AdminWindow", "Загрузить фото"))
        self.label_7.setText(_translate("AdminWindow", "Имя*"))
        self.label_6.setText(_translate("AdminWindow", "Фамилия*"))
        self.label_13.setText(_translate("AdminWindow", "Отчество"))
        self.label_8.setText(_translate("AdminWindow", "Дата рождения*"))
        self.label_9.setText(_translate("AdminWindow", "Группа*"))
        self.group.setItemText(0, _translate("AdminWindow", "None"))
        self.label_10.setText(_translate("AdminWindow", "Секретный вопрос*"))
        self.question.setItemText(0, _translate("AdminWindow", "Вопрос1"))
        self.question.setItemText(1, _translate("AdminWindow", "Вопрос2"))
        self.question.setItemText(2, _translate("AdminWindow", "Вопрос3"))
        self.label_11.setText(_translate("AdminWindow", "Ответ*"))
        self.label_3.setText(_translate("AdminWindow", "Эл. почта*"))
        self.label_12.setText(_translate("AdminWindow", "Телефон"))
        self.acceptChangesButton.setText(_translate("AdminWindow", "Подтвердить изменения"))
        self.DeleteUser.setText(_translate("AdminWindow", "Удалить пользователя"))
        self.label_2.setText(_translate("AdminWindow", "После внесения изменений, потребуется перезайти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AdminWindow", "Личный кабинет"))
        self.statisticLabel.setText(_translate("AdminWindow", "TextLabel"))
        self.viewGraphicsButton.setText(_translate("AdminWindow", "Отобразить графики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AdminWindow", "Статистика"))
        self.label_15.setText(_translate("AdminWindow", "Группа вопросов:"))
        self.label_4.setText(_translate("AdminWindow", "Список вопросов"))
        self.editQuestionButton.setText(_translate("AdminWindow", "Редактировать вопрос"))
        self.hideQuestionButton.setText(_translate("AdminWindow", "Скрыть вопрос"))
        self.hideGroupOfQuestionsButton.setText(_translate("AdminWindow", "Скрыть группу Вопросов"))
        self.deleteGroupOfQuestionsButton.setText(_translate("AdminWindow", "Удалить группу вопросов"))
        self.deleteQuestionButton.setText(_translate("AdminWindow", "Удалить вопрос"))
        self.AddQuestionButton.setText(_translate("AdminWindow", "Добавить вопрос"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("AdminWindow", "Вопросная база"))
