# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pycharmworkspace\Intellectual-testing-system\interface\Windows\recoveryRequest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecoveryRequest(object):
    def setupUi(self, RecoveryRequest):
        RecoveryRequest.setObjectName("RecoveryRequest")
        RecoveryRequest.resize(418, 355)
        self.centralwidget = QtWidgets.QWidget(RecoveryRequest)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.faternityLine = QtWidgets.QLineEdit(self.centralwidget)
        self.faternityLine.setObjectName("faternityLine")
        self.gridLayout.addWidget(self.faternityLine, 6, 1, 1, 1)
        self.passwordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLine.setObjectName("passwordLine")
        self.gridLayout.addWidget(self.passwordLine, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.emailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.emailLine.setObjectName("emailLine")
        self.gridLayout.addWidget(self.emailLine, 11, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 11, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLine.setObjectName("nameLine")
        self.gridLayout.addWidget(self.nameLine, 4, 1, 1, 1)
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.registerButton, 13, 1, 1, 1)
        self.surnameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.surnameLine.setObjectName("surnameLine")
        self.gridLayout.addWidget(self.surnameLine, 5, 1, 1, 1)
        self.group = QtWidgets.QComboBox(self.centralwidget)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.gridLayout.addWidget(self.group, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 1, 1, 1, 1)
        self.phoneLine = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneLine.setObjectName("phoneLine")
        self.gridLayout.addWidget(self.phoneLine, 12, 1, 1, 1)
        self.question = QtWidgets.QComboBox(self.centralwidget)
        self.question.setObjectName("question")
        self.gridLayout.addWidget(self.question, 9, 1, 1, 1)
        self.answerLine = QtWidgets.QLineEdit(self.centralwidget)
        self.answerLine.setObjectName("answerLine")
        self.gridLayout.addWidget(self.answerLine, 10, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.loginLine = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLine.setObjectName("loginLine")
        self.gridLayout.addWidget(self.loginLine, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.dateOfBirth = QtWidgets.QLineEdit(self.centralwidget)
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.gridLayout.addWidget(self.dateOfBirth, 7, 1, 1, 1)
        RecoveryRequest.setCentralWidget(self.centralwidget)

        self.retranslateUi(RecoveryRequest)
        QtCore.QMetaObject.connectSlotsByName(RecoveryRequest)

    def retranslateUi(self, RecoveryRequest):
        _translate = QtCore.QCoreApplication.translate
        RecoveryRequest.setWindowTitle(_translate("RecoveryRequest", "Запрос на восстановление"))
        self.label_10.setText(_translate("RecoveryRequest", "Секретный вопрос*"))
        self.label_5.setText(_translate("RecoveryRequest", "Имя*"))
        self.label_2.setText(_translate("RecoveryRequest", "Эл. почта*"))
        self.label_12.setText(_translate("RecoveryRequest", "Телефон"))
        self.label_9.setText(_translate("RecoveryRequest", "Группа*"))
        self.label_4.setText(_translate("RecoveryRequest", "Пароль*"))
        self.registerButton.setText(_translate("RecoveryRequest", "Подтвердить"))
        self.group.setItemText(0, _translate("RecoveryRequest", "18БИ1"))
        self.group.setItemText(1, _translate("RecoveryRequest", "18БИ2"))
        self.label_3.setText(_translate("RecoveryRequest", "Логин*"))
        self.label_7.setText(_translate("RecoveryRequest", "Отчество"))
        self.label_8.setText(_translate("RecoveryRequest", "Дата рождения*"))
        self.label_11.setText(_translate("RecoveryRequest", "Ответ*"))
        self.label_6.setText(_translate("RecoveryRequest", "Фамилия*"))
        self.label.setText(_translate("RecoveryRequest", "Ответ на секретный вопрос не верный, введите все данные, которые помните"))
