# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pycharmworkspace\Intellectual-testing-system\interface\Windows\user.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UI_UserWindow):
        UI_UserWindow.setObjectName("UI_UserWindow")
        UI_UserWindow.resize(411, 354)
        self.centralwidget = QtWidgets.QWidget(UI_UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.pushButton_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -124, 354, 414))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.photoView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.photoView.setObjectName("photoView")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.photoView)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_5)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.nameLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLine.setObjectName("nameLine")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLine)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.faternityLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.faternityLine.setObjectName("faternityLine")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.faternityLine)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dateOfBirth = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateOfBirth)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.group = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.group)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.question = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.question.setObjectName("question")
        self.question.addItem("")
        self.question.addItem("")
        self.question.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.question)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.answerLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.answerLine.setObjectName("answerLine")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.answerLine)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.emailLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.emailLine.setObjectName("emailLine")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.emailLine)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.phoneLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.phoneLine.setObjectName("phoneLine")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.phoneLine)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.pushButton_4)
        self.errorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.errorLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 367, 290))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        UI_UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UI_UserWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(UI_UserWindow)

    def retranslateUi(self, UI_UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_UserWindow.setWindowTitle(_translate("UI_UserWindow", "Система тестирования"))
        self.label.setText(_translate("UI_UserWindow", "Выберите тему"))
        self.pushButton.setText(_translate("UI_UserWindow", "Пройти тематический тест"))
        self.pushButton_2.setText(_translate("UI_UserWindow", "Пройти итоговый тест"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UI_UserWindow", "Тестирование"))
        self.label_14.setText(_translate("UI_UserWindow", "Фото"))
        self.pushButton_5.setText(_translate("UI_UserWindow", "Загрузить фото"))
        self.label_7.setText(_translate("UI_UserWindow", "Имя*"))
        self.label_6.setText(_translate("UI_UserWindow", "Фамилия*"))
        self.label_13.setText(_translate("UI_UserWindow", "Отчество"))
        self.label_8.setText(_translate("UI_UserWindow", "Дата рождения*"))
        self.label_9.setText(_translate("UI_UserWindow", "Группа*"))
        self.group.setItemText(0, _translate("UI_UserWindow", "18БИ1"))
        self.group.setItemText(1, _translate("UI_UserWindow", "18БИ2"))
        self.label_10.setText(_translate("UI_UserWindow", "Секретный вопрос*"))
        self.question.setItemText(0, _translate("UI_UserWindow", "Вопрос1"))
        self.question.setItemText(1, _translate("UI_UserWindow", "Вопрос2"))
        self.question.setItemText(2, _translate("UI_UserWindow", "Вопрос3"))
        self.label_11.setText(_translate("UI_UserWindow", "Ответ*"))
        self.label_3.setText(_translate("UI_UserWindow", "Эл. почта*"))
        self.label_12.setText(_translate("UI_UserWindow", "Телефон"))
        self.pushButton_3.setText(_translate("UI_UserWindow", "Подтвердить изменения"))
        self.pushButton_4.setText(_translate("UI_UserWindow", "Удалить пользователя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UI_UserWindow", "Личный кабинет"))
        self.label_4.setText(_translate("UI_UserWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("UI_UserWindow", "Статистика"))
