# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pycharmworkspace\Intellectual-testing-system\interface\Windows\user.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(411, 354)
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.questionThemeComboBox = QtWidgets.QComboBox(self.tab)
        self.questionThemeComboBox.setObjectName("questionThemeComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.questionThemeComboBox)
        self.themeTestButton = QtWidgets.QPushButton(self.tab)
        self.themeTestButton.setObjectName("themeTestButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.themeTestButton)
        self.errorTestLabel = QtWidgets.QLabel(self.tab)
        self.errorTestLabel.setText("")
        self.errorTestLabel.setObjectName("errorTestLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.errorTestLabel)
        self.genetalTestButton = QtWidgets.QPushButton(self.tab)
        self.genetalTestButton.setObjectName("genetalTestButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.genetalTestButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 354, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.photoView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.photoView.setObjectName("photoView")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.photoView)
        self.uploadPhotoButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.uploadPhotoButton.setObjectName("uploadPhotoButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uploadPhotoButton)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.nameLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLine.setObjectName("nameLine")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nameLine)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.surnameLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.surnameLine.setObjectName("surnameLine")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.surnameLine)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.faternityLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.faternityLine.setObjectName("faternityLine")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.faternityLine)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.group = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.group)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.question = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.question.setObjectName("question")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.question)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.answerLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.answerLine.setObjectName("answerLine")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.answerLine)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.emailLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.emailLine.setObjectName("emailLine")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.emailLine)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.phoneLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.phoneLine.setObjectName("phoneLine")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.phoneLine)
        self.accceptChangesButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.accceptChangesButton.setObjectName("accceptChangesButton")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.accceptChangesButton)
        self.deleteUserButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.deleteUserButton)
        self.errorChangesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.errorChangesLabel.setText("")
        self.errorChangesLabel.setObjectName("errorChangesLabel")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.errorChangesLabel)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.passwordlineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordlineEdit)
        self.dateOfBirthLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.dateOfBirthLine.setObjectName("dateOfBirthLine")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dateOfBirthLine)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 367, 290))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statisticsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.statisticsLabel.setText("")
        self.statisticsLabel.setObjectName("statisticsLabel")
        self.horizontalLayout.addWidget(self.statisticsLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Система тестирования"))
        self.label.setText(_translate("UserWindow", "Выберите тему"))
        self.themeTestButton.setText(_translate("UserWindow", "Пройти тематический тест"))
        self.genetalTestButton.setText(_translate("UserWindow", "Пройти итоговый тест"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UserWindow", "Тестирование"))
        self.label_14.setText(_translate("UserWindow", "Фото"))
        self.uploadPhotoButton.setText(_translate("UserWindow", "Загрузить фото"))
        self.label_7.setText(_translate("UserWindow", "Имя*"))
        self.label_6.setText(_translate("UserWindow", "Фамилия*"))
        self.label_13.setText(_translate("UserWindow", "Отчество"))
        self.label_8.setText(_translate("UserWindow", "Дата рождения*"))
        self.label_9.setText(_translate("UserWindow", "Группа*"))
        self.group.setItemText(0, _translate("UserWindow", "18БИ1"))
        self.group.setItemText(1, _translate("UserWindow", "18БИ2"))
        self.label_10.setText(_translate("UserWindow", "Секретный вопрос*"))
        self.label_11.setText(_translate("UserWindow", "Ответ*"))
        self.label_3.setText(_translate("UserWindow", "Эл. почта*"))
        self.label_12.setText(_translate("UserWindow", "Телефон"))
        self.accceptChangesButton.setText(_translate("UserWindow", "Подтвердить изменения"))
        self.deleteUserButton.setText(_translate("UserWindow", "Удалить пользователя"))
        self.label_2.setText(_translate("UserWindow", "После внесения изменений, потребуется перезайти"))
        self.label_4.setText(_translate("UserWindow", "Пароль*"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UserWindow", "Личный кабинет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("UserWindow", "Статистика"))
